### ISSUE TITLE
Json output instead of csv for detections

### ISSUE THREAD

**Issue by baileydauterman** [joeavanzato/Trawler#44]
I have a thought on a somewhat easy way to transition from csv to json if that is something that you're interested in. In quite a few places where detections are created to be output they look similar to this:

```
$detection = [PSCustomObject]@{
            Name = 'Narrator Missing DLL is Present'
            Risk = 'Medium'
            Source = 'Windows Narrator'
            Technique = "T1546: Event Triggered Execution"
            Meta = "File: "+$item.FullName+", Created: "+$item.CreationTime+", Last Modified: "+$item.LastWriteTime
        }
```

I think we could take the Metadata and use the object directly so it will convert to json better. i.e.:

```
$detection = [PSCustomObject]@{
            Name = 'Narrator Missing DLL is Present'
            Risk = 'Medium'
            Source = 'Windows Narrator'
            Technique = "T1546: Event Triggered Execution"
            Meta =  $item | Select FullName, CreationTime, LastWriteTime
        }
```

This way we are able to convert the PSCustomObject into proper json using the headers that correlate to the object. I think a couple helper methods could be created to easily convert to either json or csv with somewhat minimal uplift.

**Comment by joeavanzato** [comment]
This is basically along the lines of what I was thinking - allowing each detection area to have unique k:v pairs within the metadata - the main problem I saw with having universal helpers was that the actual language of the metadata for CSV output may change depending on what type of detection it is and that would make it more difficult to keep a CSV-based one universal - a JSON helper wouldn't be a problem though if done like your example above - could also include additional fields like 'Description' into the metadata to help illuminate what the fields represent.

**Comment by baileydauterman** [comment]
```powershell
function Format-MetadataToCsv($detection) {
	$output = ""

	foreach ($value in $detection.Meta | Get-Member | Where-Object MemberType -eq NoteProperty) {
		$output += "$($value.Name): $($detection.Meta.($value.Name)),"
	}

	$detection.Meta = $output.Trim(",")

	return $detection
}
```

**Comment by joeavanzato** [comment]
I am currently working on this now - going to convert each detection to have a proper object for Meta that will save well to both CSV and JSON.

**Comment by joeavanzato** [comment]
Closing this as completed as per https://github.com/joeavanzato/Trawler/commit/022cb176cbba625f46b962a62c097b514baac5a8.

I have added both CSV/JSON capability and properly formatted metadata PowerShell objects for each detection.

Moving forward, new detections should follow this standard and they will automatically work properly for both JSON and CSV outputs.
