### ISSUE TITLE
Location of pwrshsip.dll in Check-TrustProviderDLL

### ISSUE THREAD

**Issue by kirilvalev** [joeavanzato/Trawler#54]
In `function Check-TrustProviderDLL` the `pwrshsip.dll` can also be found in `C:\Windows\System32`.

**Comment by joeavanzato** [comment]
Thanks!

Changing 

`            if ($_.Name -eq 'Dll' -and $_.Value -ne 'C:\Windows\System32\WindowsPowerShell\v1.0\pwrshsip.dll'){`

to the below

`            if ($_.Name -eq 'Dll' -and $_.Value -notin @("C:\Windows\System32\pwrship.dll", "C:\Windows\System32\WindowsPowerShell\v1.0\pwrshsip.dll")){`
