### ISSUE TITLE
Malformed character escape error running script

### ISSUE THREAD

**Issue by greaterthanstar** [joeavanzato/Trawler#56]
I got a script error when it was in the Registry parsing part. 

```
parsing "C:\\Program Files (x86)\\Microsoft\\EdgeUpdate\\.*\psmachine.*\.dll" - Malformed \p{X} character escape.
At C:\Users\MyName\Downloads\trawler.ps1:11400 char:37
+ ...           if ($_.Value -match $default_hklm_com_lookups[$data.Name]){
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
```

I'm not sure what the scanned string was, let me know how I can find out if you need help.

**Comment by joeavanzato** [comment]
Hey @greaterthanstar - thanks for the heads up.  I think this is just a typo in my regex for this particular COM object - could you try re-running with the latest dev build, located here: https://github.com/joeavanzato/Trawler/blob/dev/trawler.ps1

**Comment by joeavanzato** [comment]
The latest version of the main branch should solve this problem @greaterthanstar  - please let me know if any additional errors are reported.

**Comment by greaterthanstar** [comment]
Verified issue was fixed for me. Thanks!
