### ISSUE TITLE
Change Snapshot Comparison Logic

### ISSUE THREAD

**Issue by joeavanzato** [joeavanzato/Trawler#81]
Right now, snapshot comparison is too annoying and requires a decent amount of fore-thought for each detection.

I want to completely change it to just compare all fields in a detection every time - the easiest way to do this that I am thinking is below:

* Generate a snapshot as normal
* When loading a snapshot for use, load it in and 'hash' all detections using all fields in the snapshot as input to generate a hash array
* Then when we are about to write a detection inside Write-Detection, we just generate the hash of the new detection and check if it exists in the array - if it does, it's a match and we can discard or over-write the risk to 'SnapshotMatch' or something like this.

Someone point out to me why this is a bad idea - otherwise I will make this change.

**Comment by joeavanzato** [comment]
@baileydauterman  would be curious to hear your input on this if you have any - I am going to push my ideas to the dev branch soon and would love some feedback.  I think it will be far easier to maintain long-term compared to the current way of doing snapshots and everything will, by default, be included in this manner.

**Comment by joeavanzato** [comment]
If you do have a minute, the changes are now in the dev branch - it looks much cleaner to me and will make building new detections more straight forward - no more worrying about 'building' a bespoke snapshot for that specific detection.

**Comment by joeavanzato** [comment]
https://github.com/joeavanzato/Trawler/commit/f96d3ab6094554a9d807eb4082e57e7d0c05fd59

**Comment by joeavanzato** [comment]
- [ ] Fix BITS detection misbehaving with new snapshot method for some reason
- [ ] Fix Network Connection detection misbehavior with new snapshot method for some reason

**Comment by baileydauterman** [comment]
Looked through this and it makes sense to me. Good implementation!

**Comment by joeavanzato** [comment]
Thanks for the feedback - I've also implemented a middle-ware prior to hashing which can remove certain fields across all or specific detections should they be deemed irrelevant for allow-list purposes (such as PID/LocalPort/LocalAddress for network connection based detections).
